#!/usr/bin/env bash
set -euo pipefail

# Development-only WireGuard gateway for testing TunnelPilot on the same LAN.
# This uses a dedicated interface by default so it does not disturb a user's
# existing wg0 tunnel.
#
# This script intentionally generates the client private key on the gateway/admin
# host. Delete the generated client key/config after importing the config into
# the Android device.
#
# Usage:
#   sudo WG_IFACE=tunnelpilot0 ./infra/wireguard/dev-lan-gateway.sh
#
# Optional overrides:
#   WG_IFACE=tunnelpilot0
#   WG_SUBNET=10.67.0.0/24
#   WG_SERVER_ADDRESS=10.67.0.1/24
#   WG_PORT=51820
#   CLIENT_IP=10.67.0.2/32
#   ENDPOINT_HOST=192.168.1.10
#   CLIENT_CONFIG=/root/tunnelpilot-dev-client.conf

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run this script as root (sudo)." >&2
  exit 1
fi

WG_IFACE="${WG_IFACE:-tunnelpilot0}"
WG_SUBNET="${WG_SUBNET:-10.67.0.0/24}"
WG_SERVER_ADDRESS="${WG_SERVER_ADDRESS:-10.67.0.1/24}"
WG_PORT="${WG_PORT:-51820}"
CLIENT_IP="${CLIENT_IP:-10.67.0.2/32}"
ENDPOINT_HOST="${ENDPOINT_HOST:-}"
CLIENT_CONFIG="${CLIENT_CONFIG:-/root/tunnelpilot-dev-client.conf}"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing command: $1" >&2
    exit 1
  }
}

install_deps() {
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y wireguard iptables
  elif command -v pacman >/dev/null 2>&1; then
    # Do not use -Sy here: avoid a partial Arch package upgrade.
    pacman -S --needed --noconfirm wireguard-tools iptables-nft
  else
    echo "Unsupported package manager. Install wireguard-tools/wg-quick and iptables manually." >&2
    exit 1
  fi
}

if ! command -v wg >/dev/null 2>&1 || ! command -v wg-quick >/dev/null 2>&1 || ! command -v iptables >/dev/null 2>&1; then
  install_deps
fi

require_cmd wg
require_cmd wg-quick
require_cmd iptables
require_cmd ip
require_cmd awk
require_cmd systemctl

install -d -m 700 /etc/wireguard
umask 077

WAN_IFACE="${WAN_IFACE:-$(ip route show default | awk 'NR==1 {print $5}')}"
ENDPOINT_HOST="${ENDPOINT_HOST:-$(ip -4 route get 1.1.1.1 | awk '{for (i=1; i<=NF; i++) if ($i=="src") {print $(i+1); exit}}')}"

if [[ -z "${WAN_IFACE}" || -z "${ENDPOINT_HOST}" ]]; then
  echo "Could not determine WAN interface or LAN endpoint address." >&2
  echo "Set WAN_IFACE=... and ENDPOINT_HOST=... explicitly." >&2
  exit 1
fi

SERVER_PRIVATE_KEY="/etc/wireguard/${WG_IFACE}-server_private.key"
SERVER_PUBLIC_KEY="/etc/wireguard/${WG_IFACE}-server_public.key"
CLIENT_PRIVATE_KEY="/etc/wireguard/${WG_IFACE}-client_private.key"
CLIENT_PUBLIC_KEY="/etc/wireguard/${WG_IFACE}-client_public.key"
SERVER_CONFIG="/etc/wireguard/${WG_IFACE}.conf"
SYSTEMD_UNIT="wg-quick@${WG_IFACE}"

if systemctl is-active --quiet "${SYSTEMD_UNIT}"; then
  echo "${SYSTEMD_UNIT} is already active." >&2
  echo "Stop it first or choose another WG_IFACE." >&2
  exit 1
fi

if [[ -e "${SERVER_CONFIG}" ]]; then
  backup="/etc/wireguard/${WG_IFACE}.conf.backup.$(date +%Y%m%d%H%M%S)"
  cp -a "${SERVER_CONFIG}" "${backup}"
  echo "Existing ${SERVER_CONFIG} backed up to ${backup}"
fi

if [[ ! -f "${SERVER_PRIVATE_KEY}" ]]; then
  wg genkey > "${SERVER_PRIVATE_KEY}"
fi
chmod 600 "${SERVER_PRIVATE_KEY}"
wg pubkey < "${SERVER_PRIVATE_KEY}" > "${SERVER_PUBLIC_KEY}"
chmod 644 "${SERVER_PUBLIC_KEY}"

if [[ ! -f "${CLIENT_PRIVATE_KEY}" ]]; then
  wg genkey > "${CLIENT_PRIVATE_KEY}"
fi
chmod 600 "${CLIENT_PRIVATE_KEY}"
wg pubkey < "${CLIENT_PRIVATE_KEY}" > "${CLIENT_PUBLIC_KEY}"
chmod 644 "${CLIENT_PUBLIC_KEY}"

SERVER_PRIVATE="$(cat "${SERVER_PRIVATE_KEY}")"
SERVER_PUBLIC="$(cat "${SERVER_PUBLIC_KEY}")"
CLIENT_PRIVATE="$(cat "${CLIENT_PRIVATE_KEY}")"
CLIENT_PUBLIC="$(cat "${CLIENT_PUBLIC_KEY}")"

cat > "${SERVER_CONFIG}" <<WGCONF
[Interface]
Address = ${WG_SERVER_ADDRESS}
ListenPort = ${WG_PORT}
PrivateKey = ${SERVER_PRIVATE}
SaveConfig = false
PostUp = iptables -I INPUT -p udp --dport ${WG_PORT} -j ACCEPT; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s ${WG_SUBNET} -o ${WAN_IFACE} -j MASQUERADE
PostDown = iptables -D INPUT -p udp --dport ${WG_PORT} -j ACCEPT; iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s ${WG_SUBNET} -o ${WAN_IFACE} -j MASQUERADE

[Peer]
PublicKey = ${CLIENT_PUBLIC}
AllowedIPs = ${CLIENT_IP}
WGCONF

chmod 600 "${SERVER_CONFIG}"

cat > /etc/sysctl.d/99-tunnelpilot-dev.conf <<SYSCTL
net.ipv4.ip_forward=1
SYSCTL
sysctl --system >/dev/null

cat > "${CLIENT_CONFIG}" <<CLIENTCONF
# DEVELOPMENT ONLY — generated by dev-lan-gateway.sh
# Import into TunnelPilot, then delete this file from the gateway host.

[Interface]
PrivateKey = ${CLIENT_PRIVATE}
Address = ${CLIENT_IP}
DNS = 1.1.1.1

[Peer]
PublicKey = ${SERVER_PUBLIC}
AllowedIPs = 0.0.0.0/0
Endpoint = ${ENDPOINT_HOST}:${WG_PORT}
PersistentKeepalive = 25
CLIENTCONF

chmod 600 "${CLIENT_CONFIG}"

systemctl enable --now "${SYSTEMD_UNIT}"

echo
echo "TunnelPilot development gateway is ready."
echo "WireGuard interface : ${WG_IFACE}"
echo "Gateway address     : ${WG_SERVER_ADDRESS}"
echo "Endpoint            : ${ENDPOINT_HOST}:${WG_PORT}"
echo "Client address      : ${CLIENT_IP}"
echo "Server public key   : ${SERVER_PUBLIC}"
echo "Client config       : ${CLIENT_CONFIG}"
echo
echo "Next:"
echo "  1. Transfer the client config securely to your Android device."
echo "  2. Import it in TunnelPilot."
echo "  3. Test All apps mode first."
echo "  4. Then test Selected apps mode."
echo "  5. After successful import, remove the generated client private key/config from this host."
